In [ ]:
import numpy as np

In [ ]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [ ]:
np.array([3.14,4,2,3,1])

array([3.14, 4.  , 2.  , 3.  , 1.  ])

In [ ]:
np.array([1,2,3,4],dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
a2 = np.array([[1,2,3],
              [4,5,6]])

In [ ]:
type(a2)

numpy.ndarray

In [ ]:
a2.shape

(2, 3)

In [ ]:
a2.ndim

2

In [ ]:
a2.dtype

dtype('int64')

In [ ]:
a2.size

6

In [ ]:
np.zeros([2,4], dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
np.ones([2,4], dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.full((3,5), 6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.random.random((4,4))

array([[0.91764927, 0.17542725, 0.13659622, 0.24126026],
       [0.14050627, 0.68636715, 0.7449614 , 0.38531982],
       [0.10993282, 0.92215421, 0.56814542, 0.6042675 ],
       [0.5815453 , 0.39758241, 0.70379664, 0.76667164]])

In [ ]:
np.random.random((4,4))

array([[0.762774  , 0.59838924, 0.47492475, 0.78672395],
       [0.8946364 , 0.84701264, 0.33389048, 0.48323108],
       [0.99639534, 0.60326472, 0.9885976 , 0.88354002],
       [0.70134898, 0.21833422, 0.2261381 , 0.79201656]])

In [ ]:
np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [ ]:
np.random.normal(0,1,(3,3))

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [ ]:
np.random.randint(2, 99, (3,3))

array([[57, 30, 36],
       [ 2,  2, 38],
       [55,  7, 40]])

In [ ]:
np.random.rand(4,4)

array([[0.22232139, 0.38648898, 0.90259848, 0.44994999],
       [0.61306346, 0.90234858, 0.09928035, 0.96980907],
       [0.65314004, 0.17090959, 0.35815217, 0.75068614],
       [0.60783067, 0.32504723, 0.03842543, 0.63427406]])

In [ ]:
x1 = np.random.randint(20, size = 6)

In [ ]:
x1

array([ 6,  4, 15,  3, 12,  4])

In [ ]:
x1[4], x1[0], x1[-1]

(np.int64(12), np.int64(6), np.int64(4))

In [ ]:
x2 = np.random.randint(10, size = (3,4))

In [ ]:
x2

array([[4, 8, 4, 3],
       [7, 5, 5, 0],
       [1, 5, 9, 3]])

In [ ]:
x2[0][0]

np.int64(4)

In [ ]:
x2[1][2]

np.int64(5)

In [ ]:
x2[1][2]=6

In [ ]:
x2

array([[4, 8, 4, 3],
       [7, 5, 6, 0],
       [1, 5, 9, 3]])

In [ ]:
x1[0:3]

array([ 6,  4, 15])

In [ ]:
x1[2:4]

array([15,  3])

In [ ]:
x1[::2]

array([ 6, 15, 12])

In [ ]:
x2[:2,:3]

array([[4, 8, 4],
       [7, 5, 6]])

In [ ]:
x2[:,:2]

array([[4, 8],
       [7, 5],
       [1, 5]])

In [ ]:
grid = np.arange(1,10)
grid.shape

(9,)

In [ ]:
grid.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
x = np.array([1,2,3])

In [ ]:
x.shape

(3,)

In [ ]:
x.reshape((1,3)).shape

(1, 3)

In [ ]:
x2.T

array([[4, 7, 1],
       [8, 5, 5],
       [4, 6, 9],
       [3, 0, 3]])

In [ ]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [ ]:
np.concatenate((x,y))

array([1, 2, 3, 3, 2, 1])

In [ ]:
grid = np.array([[1,2,3],
                [4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate((grid,grid))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate((grid,grid), axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
x = np.array([1,2,3])
grid = np.array([[1,2,3],
                 [4,5,6]])

In [ ]:
np.vstack((x,grid))

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
y = np.array([[99],
             [99]])
np.hstack((y,grid))

array([[99,  1,  2,  3],
       [99,  4,  5,  6]])

In [ ]:
x = np.array([9,3,2,3,1,2,2,3,4,5,1,2,3,4,5])

In [ ]:
x1,x2,x3 = np.split(x,[3,5])

In [ ]:
x1

array([9, 3, 2])

In [ ]:
a = np.arange(3)

In [ ]:
a

array([0, 1, 2])

In [ ]:
a + 5

array([5, 6, 7])

In [ ]:
b = np.ones((3,3))

In [ ]:
a.shape, b.shape

((3,), (3, 3))

In [ ]:
a + b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
c = np.arange(3).reshape((3,1))

In [ ]:
c

array([[0],
       [1],
       [2]])

In [ ]:
a + c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [ ]:
list_number = ([1,2,3])

In [ ]:
ll = np.array(list_number)

In [ ]:
sum(ll)

np.int64(6)

In [ ]:
np.sum(ll)

np.int64(6)

In [ ]:
massive_array = np.random.random(10000)
massive_array[:5]
massive_array.shape

(10000,)

In [ ]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

1.2 ms ± 372 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
6.38 µs ± 126 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [ ]:
np.mean(massive_array)

np.float64(0.4949536513342933)

In [ ]:
np.max(massive_array)

np.float64(0.9999620173413053)

In [ ]:
np.min(massive_array)

np.float64(0.00016644134026855273)

In [ ]:
dog_height = [600,470,170,430,300]
dog_height = np.array(dog_height)

np.std(dog_height)

np.float64(147.32277488562318)

In [ ]:
np.var(dog_height)

np.float64(21704.0)

In [ ]:
np.sqrt(np.var(dog_height))

np.float64(147.32277488562318)

In [ ]:
x = np.array([2,1,4,3,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [ ]:
np.argsort(x)

array([1, 0, 3, 2, 4])

In [ ]:
np.random.seed(42)
MatA = np.random.randint(0,10, size = (4,6))

In [ ]:
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [ ]:
np.sort(MatA, axis = 0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [ ]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
B = np.array([[6,5],
              [4,3],
              [2,1]])

In [ ]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

In [ ]:
np.random.seed(0)
sale_amounts = np.random.randint(20, size = (5,3))

In [ ]:
sale_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [ ]:
import pandas as pd
weekly_sales = pd.DataFrame(sale_amounts, index = ["Mon", "Tues", "Wed", "Thurs", "Fri"],
                                          columns= ["Almond Butter", "Peanut Butter", "Cashew Butter"])

In [ ]:
weekly_sales

       Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [ ]:
prices = np.array([10,8,12])

In [ ]:
butter_price = pd.DataFrame(prices, index = ["Almond Butter", "Peanut Butter", "Cashew Butter"], columns=["Price"])

In [ ]:
butter_price

               Price
Almond Butter     10
Peanut Butter      8
Cashew Butter     12

In [ ]:
weekly_sales @ butter_price

       Price
Mon      240
Tues     138
Wed      458
Thurs    232
Fri      142

In [ ]:
weekly_sales["Total Prices"] = weekly_sales @ butter_price

In [ ]:
weekly_sales

       Almond Butter  Peanut Butter  Cashew Butter  Total Prices
Mon               12             15              0           240
Tues               3              3              7           138
Wed                9             19             18           458
Thurs              4              6             12           232
Fri                1              6              7           142