In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("chipotle.tsv", sep = '\t')

In [ ]:
df.head(5)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [ ]:
df.shape

(4622, 5)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

In [ ]:
list(df.columns)

['order_id', 'quantity', 'item_name', 'choice_description', 'item_price']

In [ ]:
df.index

RangeIndex(start=0, stop=4622, step=1)

In [ ]:
df.describe

<bound method NDFrame.describe of       order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa
1            1         1                                   Izze
2            1         1                       Nantucket Nectar
3            1         1  Chips and Tomatillo-Green Chili Salsa
4            2         2                           Chicken Bowl
...        ...       ...                                    ...
4617      1833         1                          Steak Burrito
4618      1833         1                          Steak Burrito
4619      1834         1                     Chicken Salad Bowl
4620      1834         1                     Chicken Salad Bowl
4621      1834         1                     Chicken Salad Bowl

                                     choice_description item_price
0                                                   NaN     $2.39
1                                          [Clementine]     $3.39
2                                               [Apple]     $3.39
3                                                   NaN     $2.39
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98
...                                                 ...        ...
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...    $11.75
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...    $11.75
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75

[4622 rows x 5 columns]>

In [ ]:
df.describe(include = "all")

           order_id     quantity     item_name choice_description item_price
count   4622.000000  4622.000000          4622               3376       4622
unique          NaN          NaN            50               1043         78
top             NaN          NaN  Chicken Bowl        [Diet Coke]     $8.75
freq            NaN          NaN           726                134        730
mean     927.254868     1.075725           NaN                NaN        NaN
std      528.890796     0.410186           NaN                NaN        NaN
min        1.000000     1.000000           NaN                NaN        NaN
25%      477.250000     1.000000           NaN                NaN        NaN
50%      926.000000     1.000000           NaN                NaN        NaN
75%     1393.000000     1.000000           NaN                NaN        NaN
max     1834.000000    15.000000           NaN                NaN        NaN

In [ ]:
df.loc[(df.quantity == 15) || (df.item_name == "Nantucket Nectar")]

,order_id,quantity,item_name,choice_description,item_price
2,1,1,Nantucket Nectar,[Apple],$3.39
22,11,1,Nantucket Nectar,[Pomegranate Cherry],$3.39
105,46,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39
173,77,1,Nantucket Nectar,[Apple],$3.39
205,91,1,Nantucket Nectar,[Peach Orange],$3.39
436,189,1,Nantucket Nectar,[Pomegranate Cherry],$3.39
601,247,2,Nantucket Nectar,[Pineapple Orange Banana],$6.78
925,381,1,Nantucket Nectar,[Pomegranate Cherry],$3.39
1356,553,1,Nantucket Nectar,[Pomegranate Cherry],$3.39
1585,641,1,Nantucket Nectar,[Peach Orange],$3.39
1626,656,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39
1706,690,1,Nantucket Nectar,[Apple],$3.39
2162,872,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39
2379,947,2,Nantucket Nectar,[Peach Orange],$6.78
2381,947,1,Nantucket Nectar,[Apple],$3.39
2430,965,1,Nantucket Nectar,[Pomegranate Cherry],$3.39
2653,1053,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39
2818,1118,1,Nantucket Nectar,[Apple],$3.39
2838,1128,1,Nantucket Nectar,[Peach Orange],$3.39
2853,1133,1,Nantucket Nectar,[Apple],$3.39
2949,1172,1,Nantucket Nectar,[Peach Orange],$3.39
3318,1330,1,Nantucket Nectar,[Peach Orange],$3.39
3368,1351,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39
3570,1433,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,$44.25
3845,1541,1,Nantucket Nectar,[Peach Orange],$3.39
4019,1609,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39
4078,1632,1,Nantucket Nectar,[Peach Orange],$3.39

In [ ]:
df.loc[(df.quantity >= 2) & (df.item_name == "Nantucket Nectar"), ['order_id', 'quantity', 'item_name']]

      order_id  quantity         item_name
601        247         2  Nantucket Nectar
2379       947         2  Nantucket Nectar

In [ ]:
df.iloc[9]

order_id                                                              5
quantity                                                              1
item_name                                                 Steak Burrito
choice_description    [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...
item_price                                                       $9.25
Name: 9, dtype: object

In [ ]:
type(df.iloc[9])

pandas.core.series.Series

In [ ]:
df.iloc[[9]]

,order_id,quantity,item_name,choice_description,item_price
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

In [ ]:
df.iloc[3:11]

,order_id,quantity,item_name,choice_description,item_price
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25
10,5,1,Chips and Guacamole,NaN,$4.45

In [ ]:
df.iloc[3:5]

,order_id,quantity,item_name,choice_description,item_price
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [ ]:
X= df.iloc[3:5, 0:-1]
Y= df.iloc[3:5, -1]
print(Y)

3     $2.39
4    $16.98
Name: item_price, dtype: object

In [ ]:
df.item_price.dtype

dtype('O')

In [ ]:
from ast import Lambda
df.item_price = df.item_price.apply(lambda x: float(x.replace('$', '')))

In [ ]:
df.item_price.dtype

dtype('float64')

In [ ]:
df.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

In [ ]:
df["total_price"] = df["quantity"] * df["item_price"]

In [ ]:
df.head()

,order_id,quantity,item_name,choice_description,item_price,total_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,33.96

In [ ]:
revenue = df.total_price.sum()
print(revenue)

39237.02

In [ ]:
c = df.groupby("item_name")["quantity"].sum()
c.sort_values(ascending = False).head(5)

item_name
Chicken Bowl           761
Chicken Burrito        591
Chips and Guacamole    506
Steak Burrito          386
Canned Soft Drink      351
Name: quantity, dtype: int64

In [ ]:
df.item_name.value_counts().count()

np.int64(50)

In [ ]:
df.item_name.nunique()

50